//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volkswagen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string EquipId { get; set; }
        public string EquipDes { get; set; }
        public string Person { get; set; }
        public string Section { get; set; }
        public string WSArea { get; set; }
        public string Photo { get; set; }
        public string ItemInspect { get; set; }
        public string RegularCare { get; set; }
        public string Check { get; set; }
        public string RoutingInspect { get; set; }
        public string TPMFile { get; set; }
        public string Rules { get; set; }
        public string TechnicFile { get; set; }
        public string TrainingFile { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string Changer { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
    }
}
